name: chichanka_perfume
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.5
  connectivity_plus: ^6.1.3
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_keyboard_visibility: ^6.0.0
  flutter_swipe_action_cell: ^3.1.5
  get: ^4.7.2
  google_sign_in: ^6.3.0
  image_card: ^0.0.4
  lottie: ^3.3.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
